FROM hseeberger/scala-sbt:11.0.14.1_1.6.2_2.12.15

RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy curl && \
    apt-get install -qy curl && \
    curl -sSL https://get.docker.com/ | sh