environment              = "qa"
project                  = "kf-etl-clin-portal"
account                  = "kf-strides"
portal_emr_ec2_subnet_id = "subnet-0f0c909ec60b377ce"
portal_etl_bucket        = "kf-strides-232196027141-datalake-qa"
emr_instance_profile     = "kf-variant-emr-ec2-qa-profile"
emr_service_role         = "kf-variant-emr-qa-role"
elastic_search_endpoint  = "https://vpc-kf-arranger-blue-es-service-exwupkrf4dyupg24dnfmvzcwri.us-east-1.es.amazonaws.com"